sudo: false

language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

env:
    - NUMPY_VERSION=1.8
    - NUMPY_VERSION=1.9

install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION numpy=$NUMPY_VERSION scipy pytest setuptools h5py pip
    - source activate test
    - pip install pytest-cov coveralls

script:
    - python setup.py test -a "--cov emcee3 -v"

after_success:
    - coveralls
